name: Build UriDictmaker for Windows

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller PyQt5

      - name: Build with PyInstaller
        run: |
          pyinstaller `
            --onefile `
            --icon=icons/app_icon.ico `
            --name=UriDictmaker `
            --add-data "icons/*;icons" `
            --add-data "themes/*;themes" `
            --add-data "translations/*;translations" `
            main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: UriDictmaker-Windows
          path: dist/UriDictmaker.exe
