name: Build Windows EXE    

on:
  push:
    branches: [ main ]    
  release:
    types: [ published ]   

jobs:
  build-windows:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Grabs your repo files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'   

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --clean --noconfirm app.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Uri-Dictmaker
          path: dist/**/*.exe
